### PR TITLE
Generate messages for fallback languages

### LINKED ISSUE #7: Support language fallbacks in loadTwinkleCoreMessages
When I set my language to zh-tw, Twinkle failed to load messages and fallbacks to en. It's better to load zh-hant messages.

Fallback sequence: zh-tw, zh-hant, zh-hans, en.

Some info: https://www.mediawiki.org/wiki/Manual:Language#Fallback_languages

### PR DESCRIPTION
**Pull request by Xi-Plus**
1. Fill all missing messages for each language by language fallback chains.
2. Generate message for languages with fallback chains. But not for all fallback languages are missing. I don't copied messages from en.json. 

language-fallbacks.json is copied from https://github.com/jwbth/convenient-discussions/blob/87755076edd864119d8d1f7a282be7c131be81d2/language-fallbacks.json

Close #7

### CODE REVIEW

**Comment by siddharthvp** [comment]
@Xi-Plus This is good first step. But there is an issue: there could be cases where fallbacks don't have the same plural/grammar/gender rules. In such cases, the i18n lib will emit wrong outputs. Fortunately the banana lib allows handling of this case: see https://github.com/wikimedia-gadgets/orange-i18n#load-the-messages-for-many-locales-at-once. So the processed i18n files should use that format - so that the library can know the actual language of messages for correct parsing.

**Comment by siddharthvp** [comment]
Only now I realize that the i18n lib uses its known [fallbacks.json file](https://github.com/wikimedia-gadgets/orange-i18n/blob/master/src/languages/fallbacks.json) which seems outdated as it has only 160 entries. That can be updated to match language-fallbacks.json from this PR, but it can also be removed fully to reduce the size - because once we fetch a processed i18n file, the object keys will be fallback langs which we could feed to orange-i18n by creating a `setFallbackLangs()` method in it. Anyway this is a separate issue and can be handled later.

**Comment by siddharthvp** [comment]
I just modified the code to handle the above. Also I thought it would be good to include empty jsons for languages which have no messages, because Gerrit fetch for a non-existing file presently gives a CORS error for some reason, which is confusing. An empty response seems better. Even makes the code simpler!

**Comment by siddharthvp** [comment]
Looks good to go!

**Comment by siddharthvp** [comment]
Workflow run succeeded: processed files at https://github.com/wikimedia-gadgets/twinkle-core/tree/i18n/build-i18n

**Comment by Xi-Plus** [comment]
https://github.com/wikimedia-gadgets/twinkle-core/blob/a7d7d48907f54b48aaa5aea4e9d70852d47e5fbb/src/messenger.ts#L207
need to be replaced with `banana.load(json);`

**Comment by Xi-Plus** [comment]
> need to be replaced with `banana.load(json);`

I found it's unneeded. The locale parameter will be ignored.

**Pull request merged**
